/**
 * Core Domain Model: Form & FormSubmission
 * Interactive input forms and submitted record captures.
 */

import { DataSchema } from './schema.model';

export type FormStatus = 'draft' | 'published' | 'archived';
export type SubmissionStatus = 'submitted' | 'processed' | 'rejected';

export interface FormSettings {
  allowAnonymous?: boolean;
  requireSignature?: boolean;
  confirmationMessage?: string;
  autoGenerateDocument?: boolean;
  documentTemplateId?: string;
}

export interface Form {
  id: string;
  workspaceId: string;
  name: string;
  description?: string;
  status: FormStatus;
  templateId?: string;
  schema: DataSchema;
  settings?: FormSettings;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
}

export interface FormSubmission {
  id: string;
  formId: string;
  workspaceId: string;
  data: Record<string, unknown>;
  status: SubmissionStatus;
  submittedBy?: string;
  submittedAt: string;
  documentId?: string; // Generated document ID if auto-generated
  signatureUrl?: string;
  metadata?: Record<string, unknown>;
}
